// Code generated by MockGen. DO NOT EDIT.
// Source: tracks.go
//
// Generated by this command:
//
//	mockgen -source tracks.go -destination tracks_mock.go -package domain
//

// Package domain is a generated GoMock package.
package domain
